FROM arm32v7/python:3.9-bullseye

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libssl-dev libffi-dev wget tar python3.9-dev patchelf upx-ucl \
    && python3.9 -m pip install nuitka

ENV CFLAGS="-Os -march=armv7-a"
